describe('standard.h.paint', () => {
  test.todo('Executa a entidade quando for usado com o operador new')
  test.todo('Executa o component quando for usado como uma funcao')
  test.todo('Vincula na instancia o contrato paint.rootAST')
  test.todo('Vincula na instancia o contrato paint.rootElement')
  test.todo('Vincula na instancia o contrto reflow.different')
  test.todo('Vincula na instancia o contrato paint.flow')
  test.todo('Vincula na instancia o contrato paint.reflow')
  test.todo('Vincula no ast o contrato paint.instance')
})
