describe('standard.http', () => {
  test.todo('Apos o operador de acesso podemos definir qualquer metodo')
  test.todo('Transforma o response um blob')
  test.todo('Transforma os dados em um literal e inclui no corpo da requisicao')
  test.todo('Define um cache para as futuras requisicao')
  test.todo('Define os cabecalhos da requisicao')
  test.todo('Transforma o response em json')
  test.todo('Define um mode para a requisicao')
  test.todo('Vincula um signal para controlar a requisicao')
  test.todo('Transforma o response em um texto')
})
